# Generated by Django 4.2.7 on 2025-08-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_location_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(choices=[('reuniao', 'Reunião'), ('audiencia_publica', 'Audiência Pública'), ('sessao_plenaria', 'Sessão Plenária'), ('palestra', 'Palestra'), ('workshop', 'Workshop'), ('seminario', 'Seminário'), ('congresso', 'Congresso'), ('curso_capacitacao', 'Curso/Capacitação'), ('mesa_redonda', 'Mesa-Redonda'), ('debate', 'Debate'), ('conferencia', 'Conferência'), ('encontro_tematico', 'Encontro Temático'), ('assembleia', 'Assembleia'), ('visita_tecnica', 'Visita Técnica'), ('cerimonia_oficial', 'Cerimônia Oficial'), ('lancamento_projeto', 'Lançamento de Projeto/Programa'), ('coletiva_imprensa', 'Coletiva de Imprensa'), ('atividade_cultural', 'Atividade Cultural'), ('atividade_comunitaria', 'Atividade Comunitária'), ('outros', 'Outros')], max_length=50, verbose_name='Tipo'),
        ),
    ]
