# Generated by Django 5.2.5 on 2025-08-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventtype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
