# Generated by Django 5.2.5 on 2025-08-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_participant_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDocument',
        ),
    ]
