# Generated by Django 4.2.7 on 2025-08-24 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('visualizador', 'Visualizador')], default='visualizador', max_length=20, verbose_name='Tipo de Usuário')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Foto do Perfil')),
                ('receive_notifications', models.BooleanField(default=True, verbose_name='Receber Notificações')),
                ('calendar_view_preference', models.CharField(choices=[('month', 'Mensal'), ('week', 'Semanal'), ('day', 'Diário'), ('list', 'Lista')], default='month', max_length=10, verbose_name='Visualização Preferida do Calendário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.department', verbose_name='Departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Ação')),
                ('resource', models.CharField(max_length=100, verbose_name='Recurso')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('success', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
