# Generated by Django 4.2.7 on 2025-08-25 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_reportexecution_model'),
        ('reports', '0003_remove_report_model'),
    ]

    operations = [
    ]
