# Generated by Django 4.2.7 on 2025-08-25 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_eventtype_name'),
        ('reports', '0004_merge_20250824_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Relatório')),
                ('report_type', models.CharField(choices=[('events_by_period', 'Eventos por Período'), ('events_by_type', 'Eventos por Tipo'), ('events_by_department', 'Eventos por Departamento'), ('events_by_status', 'Eventos por Status'), ('participant_summary', 'Resumo de Participantes'), ('location_usage', 'Uso de Localizações'), ('monthly_summary', 'Resumo Mensal'), ('yearly_summary', 'Resumo Anual'), ('custom', 'Relatório Personalizado')], max_length=30, verbose_name='Tipo de Relatório')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_date', models.DateField(verbose_name='Data Início')),
                ('end_date', models.DateField(verbose_name='Data Fim')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Relatório Agendado')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Frequência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='Última Geração')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('departments', models.ManyToManyField(blank=True, to='events.department', verbose_name='Departamentos')),
                ('event_types', models.ManyToManyField(blank=True, to='events.eventtype', verbose_name='Tipos de Evento')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Executado em')),
                ('success', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('file_path', models.FileField(blank=True, upload_to='reports/', verbose_name='Arquivo Gerado')),
                ('records_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Registros')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Tempo de Execução (s)')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.report')),
            ],
            options={
                'verbose_name': 'Execução de Relatório',
                'verbose_name_plural': 'Execuções de Relatórios',
                'ordering': ['-executed_at'],
            },
        ),
    ]
