# Generated by Django 5.2.5 on 2025-08-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_reportexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('events_by_period', 'Eventos por Período'), ('events_by_type', 'Eventos por Tipo'), ('events_by_department', 'Eventos por Departamento'), ('events_by_status', 'Eventos por Status'), ('location_usage', 'Uso de Localizações'), ('monthly_summary', 'Resumo Mensal'), ('yearly_summary', 'Resumo Anual'), ('custom', 'Relatório Personalizado')], max_length=30, verbose_name='Tipo de Relatório'),
        ),
    ]
