# Generated by Django 4.2.7 on 2025-08-24 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_created', models.BooleanField(default=True, verbose_name='Evento Criado')),
                ('event_updated', models.BooleanField(default=True, verbose_name='Evento Atualizado')),
                ('event_cancelled', models.BooleanField(default=True, verbose_name='Evento Cancelado')),
                ('event_reminder', models.BooleanField(default=True, verbose_name='Lembrete de Evento')),
                ('event_starting', models.BooleanField(default=True, verbose_name='Evento Iniciando')),
                ('document_added', models.BooleanField(default=True, verbose_name='Documento Adicionado')),
                ('participant_added', models.BooleanField(default=False, verbose_name='Participante Adicionado')),
                ('system_alert', models.BooleanField(default=True, verbose_name='Alertas do Sistema')),
                ('reminder_hours', models.PositiveIntegerField(default=24, verbose_name='Lembrete (horas antes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('event_created', 'Evento Criado'), ('event_updated', 'Evento Atualizado'), ('event_cancelled', 'Evento Cancelado'), ('event_reminder', 'Lembrete de Evento'), ('event_starting', 'Evento Iniciando'), ('event_ended', 'Evento Finalizado'), ('document_added', 'Documento Adicionado'), ('participant_added', 'Participante Adicionado'), ('system_alert', 'Alerta do Sistema')], max_length=20, verbose_name='Tipo de Notificação')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('action_url', models.URLField(blank=True, verbose_name='URL da Ação')),
                ('action_text', models.CharField(blank=True, max_length=50, verbose_name='Texto da Ação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event', verbose_name='Evento Relacionado')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
