# Generated by Django 5.2.5 on 2025-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_participant_added_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='document_added',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_created', 'Evento Criado'), ('event_updated', 'Evento Atualizado'), ('event_cancelled', 'Evento Cancelado'), ('event_reminder', 'Lembrete de Evento'), ('event_starting', 'Evento Iniciando'), ('event_ended', 'Evento Finalizado'), ('system_alert', 'Alerta do Sistema')], max_length=20, verbose_name='Tipo de Notificação'),
        ),
    ]
